wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1687454530.571487
    t:
      1:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      3:
      - 2
      - 13
      - 23
      4: 3.10.11
      5: 0.15.4
      8:
      - 1
      - 3
      - 5
